// Used in class naming
import {
	VIEWPORT_X_LARGE_IDENTIFIER,
	VIEWPORT_LARGE_IDENTIFIER,
	VIEWPORT_MEDIUM_IDENTIFIER,
	VIEWPORT_SMALL_IDENTIFIER
} from './_scss-variables';

export default {
	X_LARGE: VIEWPORT_X_LARGE_IDENTIFIER,
	LARGE: VIEWPORT_LARGE_IDENTIFIER,
	MEDIUM: VIEWPORT_MEDIUM_IDENTIFIER,
	SMALL: VIEWPORT_SMALL_IDENTIFIER
};