// Used in class naming
import {
  VIEWPORT_X_LARGE_IDENTIFIER,
  VIEWPORT_LARGE_IDENTIFIER,
  VIEWPORT_MEDIUM_IDENTIFIER,
  VIEWPORT_SMALL_IDENTIFIER
} from './_scss-variables';

interface ViewportsConstants {
  X_LARGE: string;
  LARGE: string;
  MEDIUM: string;
  SMALL: string;
}

const VIEWPORTS: ViewportsConstants = {
  X_LARGE: VIEWPORT_X_LARGE_IDENTIFIER,
  LARGE: VIEWPORT_LARGE_IDENTIFIER,
  MEDIUM: VIEWPORT_MEDIUM_IDENTIFIER,
  SMALL: VIEWPORT_SMALL_IDENTIFIER
};

export default VIEWPORTS;